services:

  mongodb:
    image: mongo:8
    container_name: bidverse-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bidverse-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./.env.docker
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bidverse-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend 

volumes:
  mongodb_data: