services:



  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bidverse-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./.env.docker
   
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bidverse-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend 

